[package]
name = "cargo-devserver"
version = "0.2.2"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2024"
rust-version = "1.85"
description = "recompile harness for rust web app development on cfg(unix)"
license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = "1.0.102"
signal-hook = "0.4.4"
notify = "8.2.0"
log = "0.4.30"
env_logger = "0.11.10"
cargo_metadata = "0.23.1"
clap = { version = "4.6.1", features = ["derive", "env"] }

[dependencies.nix]
version = "0.31.3"
default-features = false
features = ["signal", "process", "socket", "net"]
