name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest] #, windows-latest]
        rust: [nightly, stable]
    steps:
    - uses: actions/checkout@master
    - name: Install ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.6.1

    - name: Run build
      uses: actions-rs/cargo@v1
      with:
        command: build

  check_fmt_and_udeps:
    name: Lints and Udeps
    runs-on: ubuntu-latest
    steps:
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.6.1
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
        override: true

    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
        
    - name: Format
      run: cargo fmt --all -- --check

    - name: Run cargo-udeps
      uses: aig787/cargo-udeps-action@v1
      with:
        version: 'latest'
        args: '--all-targets'

